### ISSUE TITLE
无法读取日期类型字段

### ISSUE THREAD

**Issue by idealclover** [vikadata/vika.py#10]
读取日期类型字段出现的都是None，不太符合预期

**Comment by mayneyao** [comment]
有好几种原因会造成取值为 None 
1. 单元格的值为空时候，API 不会返回改字段的值， 此时 record.<日期字段> 取值为 None
2. field_key = name 时候，record.<字段 id> 是获取不到值的，使用 record.<字段名称> 才能获取到。反之 field_key = id 同理。
3. 如果使用了 field_key_map 自己映射字段，需要自己定义的列名和 field_id 或者 field_name 匹配才能获取到。

你可以先试下 record.json() 看看原始数据中是否包含该日期字段的值。如果没有，表示单元格确实为空。如果有，检查下字段名相关的配置是否正确。

近期 API 更新会暴露字段信息，SDK 会有个优化。输入错误的 key 会给出字段不存在的提示，而不是返回 None。

**Comment by idealclover** [comment]
找到问题了，但是需要vika一起看下

在 `datasheet = vika.datasheet(TOKEN, field_key="name")` 的时候，token传的是这张表，但只返回了第一张视图的数据
比方说这张表里有1、2、3三个字段，但第一个视图中只有1、2两个字段，3被隐藏了，在调用的时候就不会返回3

在调用时能控制返回哪张视图中显示的字段吗？或者返回全量字段？

**Comment by mayneyao** [comment]
`datasheet.records.all(viewId="viwxxxxx")` 可以返回指定视图的记录，不传默认会返回第一个视图的。 
新建一个不隐藏列、不带筛选条件的视图，获取数据时，指定这个视图 id，可以暂时解决这个问题。
这个问题，下个版本也会解决的哈😂。不传视图id 默认返回全量数据，不会再和视图耦合。

**Comment by mayneyao** [comment]
> 找到问题了，但是需要vika一起看下
> 
> 在 `datasheet = vika.datasheet(TOKEN, field_key="name")` 的时候，token传的是这张表，但只返回了第一张视图的数据
> 比方说这张表里有1、2、3三个字段，但第一个视图中只有1、2两个字段，3被隐藏了，在调用的时候就不会返回3
> 
> 在调用时能控制返回哪张视图中显示的字段吗？或者返回全量字段？

现在不主动传入 viewId，返回的就是全记录，全字段。当某个字段值为空时，该字段值仍然不会返回。现在可以通过 [fields 接口](https://vika.cn/developers/docs/get-fields) 获取全部字段信息了，有助于判断字段是否存在。
