### ISSUE TITLE
单选、多选项自动添加，提供参数避免400错误

### ISSUE THREAD

**Issue by iamsk** [vikadata/vika.py#11]
![image](https://user-images.githubusercontent.com/170050/122698428-dfa5e880-d279-11eb-94cb-432be25d03b2.png)

**Comment by mayneyao** [comment]
新版 API 在路上了，会优化这个问题。如果选项不存在会自动创建，预计月底上线。

**Comment by mayneyao** [comment]
已默认支持创建不存在的选项😃
