### ISSUE TITLE
 'RecordManager' object has no attribute 'count' occurred with datasheet.records.count() 

### ISSUE THREAD

**Issue by liventang** [vikadata/vika.py#14]
运行表格右侧“API示例代码”中的示例代码报错
代码是：
```
# 返回记录总数  
records_count = datasheet.records.count()
```
错误信息是：
AttributeError: 'RecordManager' object has no attribute 'count'

PS. 其他示例代码，包括打开datasheet，返回所有记录都可正常运行。

**Comment by mayneyao** [comment]
报歉，文档没更新及时， 现在需要查询后，才能统计总数。`records_count = datasheet.records.all().count()`
