### ISSUE TITLE
Exception: 无效的维格列或函数名称：recordId

### ISSUE THREAD

**Issue by iamsk** [vikadata/vika.py#17]
版本升级后 `vika_cmb_reports.records.filter(recordId=report_id)` 报错
recordId 改为 recordIds 同样的错误，分析应该是后端server的兼容问题

**Comment by iamsk** [comment]
![image](https://user-images.githubusercontent.com/170050/139368066-768935de-6c8a-4980-9559-bff1c4d5b0f0.png)
同 `get` 可以看出对 recordIds 的处理不够严谨

**Comment by mayneyao** [comment]
> ![image](https://user-images.githubusercontent.com/170050/139368066-768935de-6c8a-4980-9559-bff1c4d5b0f0.png) 同 `get` 可以看出对 recordIds 的处理不够严谨

收到，这边处理下

**Comment by mayneyao** [comment]
> 版本升级后 `vika_cmb_reports.records.filter(recordId=report_id)` 报错 recordId 改为 recordIds 同样的错误，分析应该是后端server的兼容问题

按照现在的接口设计， get 是获取单条记录，可以改成 `vika_cmb_reports.records.get(report_id)` 获取单条记录。 filter 目前是转换成 `filterByFormula` 的公式处理

**Comment by iamsk** [comment]
好的
