### ISSUE TITLE
官网文档丢失

### ISSUE THREAD

**Issue by Fgaoxing** [vikadata/vika.py#30]
@mr-kelly 我今天一看
![image](https://user-images.githubusercontent.com/92655031/164350431-077b2ba5-12da-4c83-bef8-61867668d39b.png)

**Comment by mayneyao** [comment]
> 

具体是哪篇文档，信息可以截全一点。

**Comment by Fgaoxing** [comment]
@mayneyao 所有！

**Comment by Fgaoxing** [comment]
js也没了，对了，js有cdn引入版本吗？

**Comment by Fgaoxing** [comment]
@mayneyao

**Comment by mayneyao** [comment]
> @mayneyao
您好，可以加群沟通
![middle_img_v2_93e98364-6759-460a-8d01-56180978306g](https://user-images.githubusercontent.com/6588202/165049040-e52272b0-5394-4c24-b35c-9d6178f1285c.png)

**Comment by Fgaoxing** [comment]
@mayneyao 怎么了？写不出来了？

**Comment by mayneyao** [comment]
> @mayneyao 怎么了？写不出来了？

抱歉我们暂未明白你所反馈的问题，麻烦提供一下详细的描述，附带 URL 或者截图帮助我们理解，谢谢。

**Comment by Fgaoxing** [comment]
@mayneyao 
![image](https://user-images.githubusercontent.com/92655031/165110283-b5d422e4-bdb7-4fcc-85b0-2fbc7e73edd6.png)
只剩下cURL了，除了这个其他的也是[详情](https://vika.cn/developers/docs/get-records)

**Comment by mayneyao** [comment]
> 

感谢！排查了下，您现在访问的是旧的文档地址。正确的应该是 https://vika.cn/developers/api/get-records ，您是从搜索引擎进入的吗，还是从某篇文章的链接跳转过去的，我们这边可能有些入口没替换完。

**Comment by Fgaoxing** [comment]
@mayneyao 
![image](https://user-images.githubusercontent.com/92655031/165122751-0dda8ad0-302f-4fd5-9db6-f14cd0347c46.png)

**Comment by Fgaoxing** [comment]
@mayneyao 有cdn引入版的Javascript SDK吗?

**Comment by mayneyao** [comment]
> @mayneyao 有cdn引入版的Javascript SDK吗?

最近加了字段创建的 API，JS SDK 刚好更新了，明天发布 umd 版本的到 CDN

**Comment by Fgaoxing** [comment]
> > @mayneyao 有cdn引入版的Javascript SDK吗?
> 
> 最近加了字段创建的 API，JS SDK 刚好更新了，明天发布 umd 版本的到 CDN

@mayneyao 谢谢！CDN地址是多少？

**Comment by mayneyao** [comment]
> > > @mayneyao 有cdn引入版的Javascript SDK吗?
> > 
> > 
> > 最近加了字段创建的 API，JS SDK 刚好更新了，明天发布 umd 版本的到 CDN
> 
> @mayneyao 谢谢！CDN地址是多少？

https://cdn.jsdelivr.net/gh/vikadata/vika.js@master/dist/vika.umd.js

**Comment by Fgaoxing** [comment]
> > > > @mayneyao 有cdn引入版的Javascript SDK吗?
> > > 
> > > 
> > > 最近加了字段创建的 API，JS SDK 刚好更新了，明天发布 umd 版本的到 CDN
> > 
> > 
> > @mayneyao 谢谢！CDN地址是多少？
> 
> https://cdn.jsdelivr.net/gh/vikadata/vika.js@master/dist/vika.umd.js

太感谢了
