### ISSUE TITLE
import vika 报错

### ISSUE THREAD

**Issue by pt-cc** [vikadata/vika.py#45]
![image](https://github.com/vikadata/vika.py/assets/19907364/31bd38f3-f6e8-45ff-a232-632d4881da1b)
![image](https://github.com/vikadata/vika.py/assets/19907364/aa390d07-7ddb-4c8a-b78e-b4425f3cb3e7)
![image](https://github.com/vikadata/vika.py/assets/19907364/bfead474-9006-4f30-b330-36286bbec491)
需要指定 pydantic 版本才能使用，希望解决一下

**Comment by ziqiangai** [comment]
It seems that there is a problem with your local environment. Pydantic is not installed. I tested it and it is OK.

**Comment by pt-cc** [comment]
我在docker中安装的，你可以试试 ```alpine:latest```这个docker容器中能否正常安装。另外，Pydantic是不是作为依赖安装的，你的环境是否提前安装了Pydantic，你可以换成一个高版本的Pydantic试试，alpine:latest 这个是个全新的环境，新拉起的容器环境，上面的截图可以看到，我只是install vika，但是作为依赖安装了Pydantic。

**Comment by JoysKang** [comment]
一样的错误，Pydantic 2.0以下版本可用，2.0以上报错。

**Comment by anycell** [comment]
同样的错误

**Comment by tianluvika** [comment]
@Exclamation-mark 自强，再帮看下这里，我新建虚拟环境测试的：pip install vika同样报错，并且目前几个用户都出现了这个报错
<img width="1346" alt="image" src="https://github.com/vikadata/vika.py/assets/108800382/2eed5e10-10b6-4bd6-937e-007be5a0cd2b">
<img width="1380" alt="image" src="https://github.com/vikadata/vika.py/assets/108800382/0ff45433-9639-4b44-a103-935a5aea1407">

**Comment by dage233** [comment]
![image](https://github.com/vikadata/vika.py/assets/46173896/9a2d5c2c-fc4d-4d0e-84d7-fa47d828f4de)
setup.py没有指定版本，那就会安装最新的，限制一下Pydantic 版本应该就可以了吧

**Comment by mr-kelly** [comment]
Fix, please upgrade your sdk
```bash
pip install --upgrade vika
```
