### ISSUE TITLE
请求中指定pageNum，却返回所有记录

### ISSUE THREAD

**Issue by iamsk** [vikadata/vika.py#7]
代码 vika.py 中，与文档不符：当调用 all 时，显式地传入参数，则利用服务端计算返回部分数据集。

        if resp.success:
            records += resp.data.records
            if current_total < resp.data.total:
                kwargs.update({"pageNum": page_num + 1})
                records += self.fetch_datasheet(dst_id, **kwargs)

**Comment by mayneyao** [comment]
感谢反馈，近期修复🙏

**Comment by mayneyao** [comment]
> 代码 vika.py 中，与文档不符：当调用 all 时，显式地传入参数，则利用服务端计算返回部分数据集。
> 
> ```
>     if resp.success:
>         records += resp.data.records
>         if current_total < resp.data.total:
>             kwargs.update({"pageNum": page_num + 1})
>             records += self.fetch_datasheet(dst_id, **kwargs)
> ```

已修复，更新即可😉

**Comment by iamsk** [comment]
感谢👍
